# Generated by Django 5.0 on 2024-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailpaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
