# Generated by Django 5.0 on 2024-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailpaper", "0002_alter_newspaper_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
