# Generated by Django 3.2.20 on 2023-11-30 07:48

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taskManager.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True, validators=[taskManager.validator.validateNumber, taskManager.validator.validateReserved])),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=11)),
                ('deadline_date', models.DateField(default=datetime.date.today)),
                ('deadline_time', models.TimeField(default=datetime.time(0, 0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
