# Generated by Django 5.0 on 2024-01-19 13:38

import taskManager.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_task_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[taskManager.validator.validateNumber],
            ),
        ),
    ]
