# Generated by Django 5.0 on 2023-12-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
