# Generated by Django 5.0 on 2024-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="hidden",
            field=models.BooleanField(default=True),
        ),
    ]
